[package]
name = "metacritic_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.25", features = ["derive"] }
colored = "2.0.0"
reqwest = {version = "0.11", features = ["blocking"]}
scraper = "0.12.0"
urlencoding = "2.1.2"
